spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db
    username: asd
    password: asd
server:
  error:
    whitelabel:
      enabled: false
    path: /error