spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testdb
    username: asd
    password: asd